# Generated by Django 4.0.4 on 2022-06-26 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0008_lessonposts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='presentationVideo',
        ),
    ]
