# Generated by Django 4.0.4 on 2022-07-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0011_alter_boughtby_course_alter_boughtby_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courselesson',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
